### ISSUE TITLE
Replace defaultProps with default parameters

### ISSUE THREAD

**Issue by allanlasser** [rexxars/react-refractor#31] opened 2023-04-14 15:16 UTC
Thanks for this library!

I'm shown this warning at runtime with React 18:

```
Warning: Refractor: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

**Comment by Evavic44** [comment] 2023-08-20 11:18
Until the issue is fixed, you can silently disable the warning from the console.

```js
const error = console.error;
  console.error = (...args: any) => {
    if (/defaultProps/.test(args[0])) return;
    error(...args);
  };
```

**Comment by piscopancer** [comment] 2023-08-26 10:20
is it fixed? or what should I do to disable it completely?

**Comment by rexxars** [comment] 2024-04-08 23:20
Fixed in [v3.0.0](https://github.com/rexxars/react-refractor/releases/tag/v3.0.0).
Note that this module is now ESM-only.

**Closed as completed by rexxars** 2024-04-08 23:20 UTC
